services:

  backend:
    build: .
    container_name: med_scan_backend
    command: fastapi run main.py --port 8000 --reload
    volumes:
      - .:/opt/services/app/src:Z
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - redis_network
      - database_network
  bot:
    build: .
    container_name: med_scan_bot
    command: poetry run python /opt/app/bot/polling.py
    volumes:
      - .:/opt:Z
    env_file:
      - .env
    networks:
      - redis_network
      - database_network

  redis:
    image: redis:latest
    container_name: med_scan_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_volume:/data
    networks:
      - redis_network

  celery_worker:
    build: .
    container_name: med_scan_celery_worker
    command: celery -A app.tasks worker -l info
    volumes:
      - .:/opt/services/app/src:Z
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - redis_network
      - database_network

  celery_beat:
    build: .
    container_name: med_scan_celery_beat
    command: celery -A app.tasks beat -l info
    volumes:
      - .:/opt/services/app/src:Z
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - redis_network
      - database_network


networks:
  redis_network:
    driver: bridge

  database_network:
    driver: bridge

volumes:
  redis_volume:
  db:
